spring.application.name=bloodmatch
logging.file.name=logs/bloodmatch.log

# Shared remote MongoDB Atlas cluster connection
spring.data.mongodb.uri=mongodb+srv://rithvikakonda_db_user:66cFrSQJ9nWjZKlX@cluster0.wrqo5tw.mongodb.net/bloodmatch?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://rithvikakonda_db_user:66cFrSQJ9nWjZKlX@cluster0.wrqo5tw.mongodb.net/bloodmatch?retryWrites=true&w=majority

# SendGrid Configuration
# TODO: Replace with your actual SendGrid API Key
sendgrid.api-key=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
# TODO: Replace with your verified sender email
sendgrid.from-email=jagadeeshamudala.111@gmail.com